# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  匠心零度
subtitle: 以匠心，铸非凡！
name: 匠心零度
encoding: "utf-8"
favicon: favicon.png 

repository: jiangxinlingdu/jiangxinlingdu.github.io
github_url: https://github.com/jiangxinlingdu
cnblog_url: http://www.cnblogs.com/lirenzuo
url: http://www.jiangxinlingdu.com
enforce_ssl: jiangxinlingdu.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons
  
# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 8
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:

  -
    href: /
    label: Home

  -
    href: /rocketmq.html
    label: RocketMQ

  -
    href: /jvm.html
    label: JVM

  -
    href: /archives.html
    label: Archives

  -
    href: /link.html
    label: Link

  -
    href: /about.html
    label: About


# labels. my blog key words
labels:

  -
    href: /share/2017/10/01/resource-sharing.html
    name: 资源

  -
    href: /life.html
    name: 故事

  -
    href: /arch.html
    name: 架构
    
  -
    href: /jvm.html
    name: Jvm

  -
    href: /fastdfs.html
    name: FastDFS

  -
    href: /mongodb.html
    name: MongoDB

  -
    href: /docker.html
    name: Docker

  -
    href: /open-source.html
    name: Code   

# selected articles
classes:

  -
    href: /thought.html
    name: 技术思考
    describe: 学而不思则罔，思而不学则殆

  -
    href: /interview.html
    name: 面试系列文章
    describe: 收集整理面试，查缺补漏

  -
    href: /practice.html
    name: 实践系列文章
    describe: 实践是检验真理的唯一标准，实践是认识的最终目的


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: jiangxinlingdu
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: jiangxinlingdu
    repo: blog-comments
    oauth:
        client_id: 64e8fc2d60b13b6d506e
        client_secret: d7ba4f09445e08fb307390459cd5c8f4baeee746
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: jiangxinlingdu
    repo: blog-comments
    clientID: 64e8fc2d60b13b6d506e
    clientSecret: d7ba4f09445e08fb307390459cd5c8f4baeee746
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
